FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
# Only production deps
RUN npm ci --only=production --prefer-offline

COPY . .

EXPOSE 3001

ENV NODE_ENV=production

CMD ["node", "server.js"]
